#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

export TASKDATA="$PWD/t/tasks"
export TASKRC="$PWD/t/taskrc"

if [[ "$#" -eq 0 ]]; then
  task
fi

cmd="$1"
git checkout "$TASKDATA"
case "$cmd" in
  test )
    bundle exec vim-flavor test
    ;;
  setup )
    exit 0
    ;;
  * )
    task "${@}"
    ;;
esac
